# -*- coding: utf-8 -*-
"""Untitled19.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19YigyNuEj6Ukzhx4CP71Egtz45vZUKtc
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split, RandomizedSearchCV
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, roc_auc_score
import joblib
import gradio as gr
import warnings

warnings.filterwarnings('ignore')

# ---------------------------------------------------------
# 1. VERİ YÜKLEME VE ÖZELLİK MÜHENDİSLİĞİ (FEATURE ENGINEERING)
# ---------------------------------------------------------
df = pd.read_csv('heart_failure_clinical_records_dataset.csv')

def feature_engineering(data):
    # Orijinal veriyi bozmamak için kopyasını alıyoruz
    df_eng = data.copy()

    # a. Böbrek ve Yaş İndeksi (Kreatinin * Yaş)
    df_eng['renal_age_index'] = df_eng['serum_creatinine'] * df_eng['age']

    # b. EF Risk Kategorisi (0: Normal, 1: Orta, 2: Ciddi Risk)
    df_eng['EF_Category'] = pd.cut(df_eng['ejection_fraction'],
                                   bins=[-1, 30, 45, 100],
                                   labels=[2, 1, 0]).astype(int)

    # c. Log Dönüşümleri (Log CPK ve Log Platelets)
    df_eng['log_CPK'] = np.log1p(df_eng['creatinine_phosphokinase'])
    df_eng['log_platelets'] = np.log1p(df_eng['platelets'])

    # d. Sodyum / Kreatinin Oranı
    df_eng['sodium_creatinine_ratio'] = df_eng['serum_sodium'] / df_eng['serum_creatinine']

    return df_eng

df_processed = feature_engineering(df)

# 'time' değişkenini leakage (sızıntı) önlemek için çıkarıyoruz!
# Ayrıca işlediğimiz ham sütunları da çıkarıyoruz.
features_to_drop = ['time', 'creatinine_phosphokinase', 'platelets', 'DEATH_EVENT']
X = df_processed.drop(features_to_drop, axis=1)
y = df_processed['DEATH_EVENT']

# Eğitim ve Test setlerine ayırma
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# ---------------------------------------------------------
# 2. MODEL EĞİTİMİ (GRADIENT BOOSTING)
# ---------------------------------------------------------
print("Model eğitimi başlıyor...")

# Gradient Boosting Modeli (Random Forest'a güçlü bir alternatif)
gbc = GradientBoostingClassifier(random_state=42)

# Hiperparametre optimizasyonu
params = {
    'n_estimators': [50, 100, 200],
    'learning_rate': [0.01, 0.05, 0.1],
    'max_depth': [3, 4, 5],
    'subsample': [0.6, 0.8, 1.0],
    'min_samples_split': [2, 5, 10]
}

random_search = RandomizedSearchCV(
    gbc, param_distributions=params, n_iter=20, scoring='f1', n_jobs=-1, cv=5, random_state=42
)

random_search.fit(X_train, y_train)
best_model = random_search.best_estimator_

# Sonuçları Yazdır
y_pred = best_model.predict(X_test)
print("-" * 30)
print(f"En İyi Parametreler: {random_search.best_params_}")
print(f"Test Accuracy: {accuracy_score(y_test, y_pred):.4f}")
print(f"ROC-AUC Skoru: {roc_auc_score(y_test, best_model.predict_proba(X_test)[:, 1]):.4f}")
print("-" * 30)

# Modeli kaydet
joblib.dump(best_model, 'heart_failure_gb_model.pkl')

# ---------------------------------------------------------
# 3. GRADIO ARAYÜZÜ (INTERACTIVE UI)
# ---------------------------------------------------------
def predict_death_event(age, anaemia, cpk, diabetes, ef, hbp, platelets, serum_creatinine, serum_sodium, sex, smoking):
    # Girdi verilerini DataFrame'e çevir
    input_data = pd.DataFrame({
        'age': [age],
        'anaemia': [anaemia],
        'creatinine_phosphokinase': [cpk],
        'diabetes': [diabetes],
        'ejection_fraction': [ef],
        'high_blood_pressure': [hbp],
        'platelets': [platelets],
        'serum_creatinine': [serum_creatinine],
        'serum_sodium': [serum_sodium],
        'sex': [sex],
        'smoking': [smoking]
    })

    # Feature Engineering fonksiyonunu burada da uyguluyoruz!
    # (Model eğitiminde ne yaptıysak, tahminde de aynısını yapmalıyız)
    input_processed = feature_engineering(input_data)

    # Gereksiz sütunları at (target yok zaten, sadece ham sütunlar)
    cols_to_drop = ['creatinine_phosphokinase', 'platelets']
    input_ready = input_processed.drop(cols_to_drop, axis=1)

    # Tahmin
    prob = best_model.predict_proba(input_ready)[:, 1][0]
    prediction = "Yüksek Risk ⚠️" if prob > 0.5 else "Düşük Risk ✅"

    return f"Tahmin: {prediction}\nÖlüm Riski Olasılığı: %{prob*100:.2f}"

# Arayüz Bileşenleri
inputs = [
    gr.Slider(40, 95, label="Yaş"),
    gr.Radio([0, 1], label="Anemi (0:Yok, 1:Var)"),
    gr.Number(label="CPK (Enzim Seviyesi)", value=582),
    gr.Radio([0, 1], label="Diyabet (0:Yok, 1:Var)"),
    gr.Slider(10, 80, label="Ejection Fraction (Kalp Pompalama %)"),
    gr.Radio([0, 1], label="Yüksek Tansiyon (0:Yok, 1:Var)"),
    gr.Number(label="Platelets (Trombosit)", value=265000),
    gr.Slider(0.5, 10.0, label="Serum Kreatinin"),
    gr.Slider(110, 150, label="Serum Sodyum"),
    gr.Radio([0, 1], label="Cinsiyet (0:Kadın, 1:Erkek)"),
    gr.Radio([0, 1], label="Sigara (0:Hayır, 1:Evet)")
]

iface = gr.Interface(
    fn=predict_death_event,
    inputs=inputs,
    outputs="text",
    title="Kalp Yetmezliği Risk Tahminleyicisi (Gelişmiş Model)",
    description="Hasta değerlerini girerek ölüm riskini hesaplayın. Model 'time' değişkeninden bağımsız olarak tıbbi belirteçleri kullanır."
)

if __name__ == "__main__":
    iface.launch()

